_btn_node_routing_control:
    resource: "@BtnNodeBundle/Resources/config/routing/control.yml"
    prefix: /control

# _btn_node_routing_front:
#     resource: "@BtnNodeBundle/Resources/config/routing/front.yml"
#     prefix: /
